import { createTheme, type MantineColorsTuple, type CSSVariablesResolver } from '@mantine/core'

// Sky (Tailwind) — accent / interaction. primaryShade picks 4 in dark (bright),
// 6 in light (darker for contrast on white).
const accent: MantineColorsTuple = [
  '#f0f9ff',
  '#e0f2fe',
  '#bae6fd',
  '#7dd3fc',
  '#38bdf8',
  '#0ea5e9',
  '#0284c7',
  '#0369a1',
  '#075985',
  '#0c4a6e',
]
// Dark surface ladder: aligned with the Binsight technical palette.
// index: 0 text … 5 border, 6 panel2, 7 panel, 8 bg, 9 deepest.
const dark: MantineColorsTuple = [
  '#f0f6fc',
  '#c9d1d9',
  '#8b949e',
  '#6e7681',
  '#445875',
  '#2d3b4f',
  '#212c3d',
  '#161f2c',
  '#10151d',
  '#0b0f14',
]
// Semantic scales (Tailwind Emerald/Amber/Rose/Violet/Teal) — badges use
// `color={name} variant="light"`; Mantine derives the per-scheme tint.
const green: MantineColorsTuple = [
  '#ecfdf5',
  '#d1fae5',
  '#a7f3d0',
  '#6ee7b7',
  '#34d399',
  '#10b981',
  '#059669',
  '#047857',
  '#065f46',
  '#064e3b',
]
const orange: MantineColorsTuple = [
  '#fffbeb',
  '#fef3c7',
  '#fde68a',
  '#fcd34d',
  '#fbbf24',
  '#f59e0b',
  '#d97706',
  '#b45309',
  '#92400e',
  '#78350f',
]
const red: MantineColorsTuple = [
  '#fff1f2',
  '#ffe4e6',
  '#fecdd3',
  '#fda4af',
  '#fb7185',
  '#f43f5e',
  '#e11d48',
  '#be123c',
  '#9f1239',
  '#881337',
]
const grape: MantineColorsTuple = [
  '#f5f3ff',
  '#ede9fe',
  '#ddd6fe',
  '#c4b5fd',
  '#a78bfa',
  '#8b5cf6',
  '#7c3aed',
  '#6d28d9',
  '#5b21b6',
  '#4c1d95',
]
const teal: MantineColorsTuple = [
  '#f0fdfa',
  '#ccfbf1',
  '#99f6e4',
  '#5eead4',
  '#2dd4bf',
  '#14b8a6',
  '#0d9488',
  '#0f766e',
  '#115e59',
  '#134e4a',
]

export const theme = createTheme({
  primaryColor: 'accent',
  primaryShade: { light: 6, dark: 4 },
  white: '#ffffff',
  colors: { accent, dark, green, orange, red, grape, teal },
  autoContrast: true,
  fontFamily: '-apple-system, "Segoe UI", sans-serif',
  fontFamilyMonospace: "'SF Mono', ui-monospace, Menlo, monospace",
  defaultRadius: 'sm',
  fontSizes: { xs: '11px', sm: '12px', md: '13px', lg: '16px', xl: '20px' },
  components: {
    Button: { defaultProps: { size: 'xs' } },
    TextInput: { defaultProps: { size: 'xs' } },
    NumberInput: { defaultProps: { size: 'xs' } },
    Select: { defaultProps: { size: 'xs' } },
    MultiSelect: { defaultProps: { size: 'xs' } },
    Tooltip: {
      defaultProps: { multiline: true },
      styles: { tooltip: { maxWidth: 'min(440px, 60vw)', whiteSpace: 'normal', wordBreak: 'break-word' } },
    },
    TooltipFloating: {
      styles: { tooltip: { maxWidth: 'min(440px, 60vw)', whiteSpace: 'normal', wordBreak: 'break-word' } },
    },
  },
})

const darkTokens = {
  bg: '#0b0f14',
  panel: '#10151d',
  panel2: '#161f2c',
  elev: '#1c2736',
  border: '#2d3b4f',
  borderSubtle: '#212c3d',
  text: '#f0f6fc',
  text2: '#c9d1d9',
  muted: '#8794a0',
  accent: '#38bdf8',
  accentHi: '#7dd3fc',
  accentSoft: 'rgba(56,189,248,.12)',
  surfaceActive: 'rgba(56,189,248,.08)',
  green: '#34d399',
  orange: '#fbbf24',
  red: '#fb7185',
  grape: '#a78bfa',
  teal: '#2dd4bf',
  indigo: '#818cf8',
  sevCritical: '#fb7185',
  sevHigh: '#fb7185',
  sevMedium: '#fbbf24',
  sevLow: '#8794a0',
  warn: '#fbbf24',
  warnBg: 'rgba(251,191,36,.13)',
  warnRowBg: 'rgba(251,191,36,.13)',
  warnRowHover: 'rgba(251,191,36,.20)',
  warnBorder: '#fbbf24',
  diffOk: '#34d399',
  diffDisBg: 'rgba(251,113,133,.16)',
  diffDisBar: '#fb7185',
} as const
type Tokens = Record<keyof typeof darkTokens, string>
const lightTokens: Tokens = {
  bg: '#eef2f6',
  panel: '#ffffff',
  panel2: '#f1f5f9',
  elev: '#ffffff',
  border: '#d6dee6',
  borderSubtle: '#e2e8ef',
  text: '#13202b',
  text2: '#3d4c59',
  muted: '#5f6e7a',
  accent: '#0284c7',
  accentHi: '#036aa1',
  accentSoft: 'rgba(2,132,199,.10)',
  surfaceActive: '#ddeefb',
  green: '#059669',
  orange: '#d97706',
  red: '#e11d48',
  grape: '#7c3aed',
  teal: '#0d9488',
  indigo: '#4f46e5',
  sevCritical: '#e11d48',
  sevHigh: '#e11d48',
  sevMedium: '#d97706',
  sevLow: '#5f6e7a',
  warn: '#d97706',
  warnBg: 'rgba(217,119,6,.10)',
  warnRowBg: 'rgba(217,119,6,.10)',
  warnRowHover: 'rgba(217,119,6,.17)',
  warnBorder: '#d97706',
  diffOk: '#059669',
  diffDisBg: '#fff1f2',
  diffDisBar: '#e11d48',
}
function vars(t: Tokens, scheme: 'light' | 'dark'): Record<string, string> {
  return {
    'color-scheme': scheme,
    '--bg': t.bg,
    '--panel': t.panel,
    '--panel2': t.panel2,
    '--elev': t.elev,
    '--border': t.border,
    '--border-subtle': t.borderSubtle,
    '--text': t.text,
    '--text2': t.text2,
    '--muted': t.muted,
    '--accent': t.accent,
    '--accent-hi': t.accentHi,
    '--accent-soft': t.accentSoft,
    '--surface-active': t.surfaceActive,
    '--green': t.green,
    '--orange': t.orange,
    '--red': t.red,
    '--grape': t.grape,
    '--teal': t.teal,
    '--indigo': t.indigo,
    '--sev-critical-text': t.sevCritical,
    '--sev-high-text': t.sevHigh,
    '--sev-medium-text': t.sevMedium,
    '--sev-low-text': t.sevLow,
    '--warn': t.warn,
    '--warn-bg': t.warnBg,
    '--warn-row-bg': t.warnRowBg,
    '--warn-row-hover': t.warnRowHover,
    '--warn-border': t.warnBorder,
    '--diff-ok': t.diffOk,
    '--diff-dis-bg': t.diffDisBg,
    '--diff-dis-bar': t.diffDisBar,
  }
}
export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    '--mono': "'SF Mono', ui-monospace, Menlo, monospace",
    '--fs-sm': '11px',
    '--fs-base': '13px',
    '--fs-lg': '16px',
    '--fs-xl': '20px',
  },
  light: vars(lightTokens, 'light'),
  dark: vars(darkTokens, 'dark'),
})
